realtime_visualization/knnector/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', include(admin.site.urls)),
    url(r'^authenticate/', include('logins.urls', namespace='logins')),
    url(r'^map_system/', include('map_system.urls', namespace='maps')),
    url(r'^map_service/', include('map_service.urls', namespace='services')),
    url(r'^$', 'map_system.views.base_map', name='default'),
]

realtime_visualization/logins/urls.py
__author__ = 'tmkasun'

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^login$', views.login, name='login'),
    url(r'^login_submit', views.submit, name='submit')
]

realtime_visualization/map_service/urls.py
__author__ = 'tmkasun'

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^speed_alert$', views.get_speed_alert, name='get_speed'),
    url(r'^set_speed_alert', views.set_speed_alert, name='set_speed'),

    url(r'^proximity_alert', views.estimate_trend, name='estimate_trend'),
    url(r'^set_proximity_alert', views.set_proximity_alert, name='set_proximity'),

    url(r'geofencing', views.geofence_alert, name='get_geofence'),
    url(r'set_geofence', views.set_geofence_alert, name='set_geofence'),

    url(r'stationery_alert', views.get_stationery_alert, name='get_stationery'),
    url(r'.*',views.service_not_available, name='no_service')

]

realtime_visualization/map_system/urls.py
__author__ = 'tmkasun'

from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'base', views.base_map, name='base'),
    # url(r'.*', views.base_map, name='default')
]

realtime_visualization/logins/models.py
from django.db import models

# Create your models here.

realtime_visualization/map_service/models.py
from django.db import models

# Create your models here.

realtime_visualization/map_system/models.py
from django.db import models

# Create your models here.

realtime_visualization/logins/views.py
from django.core.urlresolvers import reverse
from django.http.response import HttpResponse, Http404, HttpResponseRedirect
from django.shortcuts import render
from django.views.decorators.http import require_http_methods


def login(request):
    page_title = "Welcome to Knnector."
    context = {
        'page_title': page_title
    }
    return render(request, 'logins/content/index.html', context=context)


@require_http_methods(['POST'])
def submit(request):
    user = request.POST['user_email']
    password = request.POST['user_password']
    remember = False
    if request.POST.has_key('user_remember') and request.POST['user_remember'] == 'True':
        remember = True
    is_valid = _validate_user(user, password)
    if is_valid:
        return HttpResponseRedirect(reverse('maps:base'))
    raise Http404('Invalid username page not created yet.')


def _validate_user(user, password):
    if user == 'kasun@knnect.com' and password == 'kasun':
        return True
    return False

realtime_visualization/map_service/views.py
from django.http.response import HttpResponse, JsonResponse, Http404
from django.shortcuts import render

from lib.wso2.services.eventProcessorAdminService import EventProcessor
from lib.trend_prediction import Prediction
import os
import re

from datetime import datetime

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

predictions = Prediction()
predictions.create_linear_model()


def estimate_trend(request):
    context = {
        'scatter_diagram': "images/figs/" + predictions.generate_scatter(),
        'regression_line': "images/figs/" + predictions.estimate_trend_line(),
    }
    return render(request, 'map_service/alerts/estimate_trend.html', context=context)


def set_proximity_alert(request):
    selected_date = request.POST['selected_date']
    date_format = "%m/%d/%Y"
    selected_date = datetime.strptime(selected_date, date_format)
    predicted_density = predictions.sckit_lm_predict(selected_date)
    return JsonResponse({'predicted_density': predicted_density[0][0]})


def get_speed_alert(request):
    speed_value = -1  # TODO: This value should fetch from organization.globals.speed_limit {MongoDB}
    context = {
        'speed_value': speed_value
    }
    return render(request, 'map_service/alerts/speed.html', context=context)


def set_speed_alert(request):
    speed_limit = request.POST['speedAlertValue']
    alert_template = open(os.path.join(BASE_DIR, 'map_service/templates/map_service/xml/geo_speed_alert.xml'))
    placeholder_pattern = re.compile(r'\$speedAlertValue')
    alert_query = placeholder_pattern.sub(speed_limit, alert_template.read())

    evnt_proc = EventProcessor()
    exe_plan_name = 'geo_speed_alert'
    exe_plan = evnt_proc.getActiveExecutionPlanConfiguration(exe_plan_name)
    if exe_plan:
        response = evnt_proc.editActiveExecutionPlanConfiguration(alert_query, exe_plan_name)
    else:
        response = evnt_proc.deployExecutionPlanConfigurationFromConfigXml(alert_query)

    return JsonResponse({'status': True})


def geofence_alert(request):
    """
    A geofence is a virtual barrier. Programs that incorporate geo-fencing allow an administrator to set up triggers
    so when a device enters (or exits) the boundaries defined by the administrator, a popup message or email alert is sent.
    :param request:
    :return:
    """
    geofences = [
        {
            'areaName': 'Test_name_1',
            'queryName': 'Testing_query_name_1',
            'createdTime': datetime.now(),
            'geoJson': {
                'geoJsonStructure': True
            }
        }, {
            'areaName': 'Test_name_2',
            'queryName': 'Testing_query_name_2',
            'createdTime': datetime.now(),
            'geoJson': {
                'geoJsonStructure': True
            }
        }, {
            'areaName': 'Test_name_3',
            'queryName': 'Testing_query_name_3',
            'createdTime': datetime.now(),
            'geoJson': {
                'geoJsonStructure': True
            }
        },
    ]
    context = {
        'geofences': geofences
    }
    return render(request, 'map_service/alerts/within.html', context=context)


def set_geofence_alert(request):
    queryName = 'geo_within_' + request.POST[
        'queryName'] + '_alert'  # TODO: Use this name to store the query in Database or remove this completly and use the area name only
    areaName = request.POST['areaName']
    geoFenceGeoJSON = request.POST['geoFenceGeoJSON']

    alert_template = open(os.path.join(BASE_DIR, 'map_service/templates/map_service/xml/geo_within_alert.xml'))
    placeholder_pattern = re.compile(r'\$areaName')
    alert_query = placeholder_pattern.sub(areaName, alert_template.read())

    placeholder_pattern = re.compile(r'\$geoFenceGeoJSON')
    alert_query = placeholder_pattern.sub(geoFenceGeoJSON, alert_query)

    placeholder_pattern = re.compile(r'\$executionPlanName')
    alert_query = placeholder_pattern.sub(queryName, alert_query)

    evnt_proc = EventProcessor()
    evnt_proc.deployExecutionPlanConfigurationFromConfigXml(alert_query)

    return JsonResponse({'status': True})


def get_stationery_alert(request):
    raise Http404("Not implemented yet")


def service_not_available(request):
    raise Http404("Not implemented yet")

realtime_visualization/map_system/views.py
from django.http.response import HttpResponse
from django.shortcuts import render


def base_map(request):
    context = {
        'page_title': "Knnect Spatial Object Analysis and Prediction System"
    }
    return render(request, 'map_system/content/base_map.html', context=context)

realtime_visualization/logins/templates/logins/commons/header.html
<!DOCTYPE html>
<html>
<head lang="en">
    {% load staticfiles %}
    <meta charset="UTF-8">
    {#  Load style sheets  #}
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap/css/bootstrap-theme.css' %}">

    {#  Load java script libraries  #}
    <script src="{% static 'jquery/jquery-2.1.4.js' %}"></script>
    <script src="{% static 'bootstrap/js/bootstrap.js' %}"></script>

    <title>{{ page_title }}</title>
</head>
<body>
{% block body %}

{% endblock %}
</body>
</html>

realtime_visualization/logins/templates/logins/content/index.html
{% extends 'logins/commons/header.html' %}
{% load staticfiles %}
{% block body %}

    <script src="{% static 'logins/js/TweenLite.min.js' %}"></script>
    <script src="{% static 'logins/js/parallax_effect.js' %}"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'logins/css/parallax_effect.css' %}"/>

    <div class="container">

        <div class="card card-container">
            <img id="profile-img" class="profile-img-card" src="{% static 'logins/images/avatar_2x.png' %}">

            <p id="profile-name" class="profile-name-card"></p>

            <form class="form-signin" action="{% url 'logins:submit'%}" method="POST">
                {% csrf_token %}
                <span id="reauth-email" class="reauth-email"></span>
                <input type="email" name="user_email" id="inputEmail" class="form-control" placeholder="Email address" required=""
                       autofocus="">
                <input type="password" name="user_password" id="inputPassword" class="form-control" placeholder="Password" required="">

                <div id="remember" class="checkbox">
                    <label>
                        <input name="user_remember" type="checkbox" value="True"> Remember me
                    </label>
                </div>
                <button class="btn btn-lg btn-primary btn-block btn-signin" type="submit">Sign in</button>
            </form>
            <a href="#" class="forgot-password">
                Forgot the password?
            </a>
        </div>
    </div>

{% endblock %}

realtime_visualization/map_service/templates/map_service/alerts/estimate_trend.html
<!DOCTYPE html>
<html>
<head lang="en">
    {% load staticfiles %}
    <link href="{% static 'libraries/leaflet/grid/L.Grid.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'libraries/leaflet/grid/L.Grid.js' %}"></script>
    <script src="{% static 'libraries/leaflet/editableHandlers/src/L.MeasuringTool.js' %}"></script>
    <style>
        {
            # TODO: move this styles to separate proximity . css file #
        }
        .leaflet-grid-label .lng {
            margin-left: 8px;
            -webkit-transform: rotate(90deg);
            transform: rotate(90deg);
        }

        .measuring-line-for-look {
            stroke-dasharray: 3, 20;
        }

        .measuring-label-tooltip .leaflet-popup-content-wrapper {
            border-radius: 4px 4px 4px 4px;
            opacity: 0.7;
            padding: 1px;
            text-align: center;
        }

        .measuring-label-tooltip .leaflet-popup-content {
            margin: 0 5px;
            /*width: 0;*/
        }

        .measuring-label-tooltip .leaflet-popup-tip-container {
            display: none;
        }
    </style>
</head>
<body>
<div class="modal-header"
     style="cursor: move;background: #f9f9f9;-webkit-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);-moz-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);">
    <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">
        <!-- TODO: Trigger bootstrap tooltip $('#aboutTileUrl').tooltip(); to enable tooltip -->
        Trend Prediction
    </h4>
</div>
<div class="modal-body">
    <div class="row">

        <div id="predication_charts" class="col-md-10 col-md-offset-1" style="height: 200px">
            <div class="row">
                <div class="col-xs-6 col-md-6"><img src="{% static scatter_diagram %}"></div>
                <div class="col-xs-6 col-md-6"><img src="{% static regression_line %}"></div>
            </div>


        </div>
        <div class="row">
            <div class="col-md-6 col-md-offset-3">

                <div id="sandbox-container">

                </div>
                <script>
                    var dataset_starting_date = new Date('2000-11-01');
                    $('#sandbox-container').datepicker({
                        minDate: dataset_starting_date
                    });
                    $('#sandbox-container').datepicker('setDate', dataset_starting_date);
                    $('#sandbox-container').datepicker('update');

                    function setProximityAlert() {

                        var selected_date = $('#sandbox-container').val();
//                        alert(selected_date);
                        var data = {
                            'selected_date': selected_date
                        };
                        setAjaxNotify("Generating prediction....");
                        // TODO: Use django composer
                        $.post('/map_service/set_proximity_alert', data, function (response) {
                            console.log(response);
                            $('#predication_charts').html(response['predicted_density'])
                        }, 'json');
                    }


                </script>
            </div>
        </div>

        <div style="margin-bottom: -15px" class="btn-group btn-group-justified">
            <div class="btn-group">
                <button style="background-color: #f4f4f4;" type="button" class="btn btn-default"
                        onclick="setProximityAlert()">Get Prediction
                </button>
            </div>
            <div class="btn-group">
                <button style="background-color: #f4f4f4;" type="button" class="btn  btn-default"
                        onclick="closeAll()">Cancel
                </button>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'local/trend_estimate.js' %}"></script>
</body>
</html>

realtime_visualization/map_service/templates/map_service/alerts/proximity.html
<!DOCTYPE html>
<html>
<head lang="en">
    {% load staticfiles %}
    <link href="{% static 'libraries/leaflet/grid/L.Grid.css' %}" rel="stylesheet" type="text/css"/>
    <script src="{% static 'libraries/leaflet/grid/L.Grid.js' %}"></script>
    <script src="{% static 'libraries/leaflet/editableHandlers/src/L.MeasuringTool.js' %}"></script>
    <style>
        {#    TODO: move this styles to separate proximity.css file#}
        .leaflet-grid-label .lng {
            margin-left: 8px;
            -webkit-transform: rotate(90deg);
            transform: rotate(90deg);
        }

        .measuring-line-for-look {
            stroke-dasharray: 3, 20;
        }

        .measuring-label-tooltip .leaflet-popup-content-wrapper {
            border-radius: 4px 4px 4px 4px;
            opacity: 0.7;
            padding: 1px;
            text-align: center;
        }

        .measuring-label-tooltip .leaflet-popup-content {
            margin: 0 5px;
            /*width: 0;*/
        }

        .measuring-label-tooltip .leaflet-popup-tip-container {
            display: none;
        }
    </style>
</head>
<body>
<div class="modal-header"
     style="cursor: move;background: #f9f9f9;-webkit-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);-moz-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);">
    <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">
        <!-- TODO: Trigger bootstrap tooltip $('#aboutTileUrl').tooltip(); to enable tooltip -->
        Define proximity
    </h4>
</div>
<div class="modal-body">
    <div class="row">

        <div class="col-md-10 col-md-offset-1" style="height: 300px">
            <div id="proximityMap" style="width: 100%;height: 100%;">

            </div>

        </div>
        <div class="row">
            <div class="col-md-10 col-md-offset-1">
                <form class="form-inline" role="form">
                    <div class="input-group input-group-sm">
                        <input type="text" id="proximityDistance" class="form-control" placeholder="Distance"
                               value="{{ proximity_distance }}">
                        {% csrf_token %}
                        <span class="input-group-addon">m</span>
                    </div>
                    <div class="input-group input-group-sm">
                        <input autofocus="enable" id="proximityTime" type="number" class="form-control"
                               placeholder="Close time in S" value="{{ proximity_time }}">
                        <span class="input-group-addon">Seconds</span>
                    </div>
                </form>
            </div>
        </div>

        <div style="margin-bottom: -15px" class="btn-group btn-group-justified">
            <div class="btn-group">
                <button style="background-color: #f4f4f4;" type="button" class="btn btn-default"
                        onclick="setProximityAlert()">Set Proximity
                </button>
            </div>
            <div class="btn-group">
                <button style="background-color: #f4f4f4;" type="button" class="btn  btn-default"
                        onclick="closeAll()">Cancel
                </button>
            </div>
        </div>
    </div>
</div>

<script src="{% static 'local/geo_proximity.js' %}"></script>
</body>
</html>

realtime_visualization/map_service/templates/map_service/alerts/speed.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
</head>
<body>
{#<%#}
{#var get = require('../get_alerts.jag').get;#}
{#%>#}
<div class="modal-header" style="cursor: move;background: #f9f9f9;-webkit-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);-moz-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);">
    <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">
        <!-- TODO: Trigger bootstrap tooltip $('#aboutTileUrl').tooltip(); to enable tooltip -->
        Setup globel speed limit
    </h4>
</div>
<div class="modal-body">
    <div class="row">
        <div class="col-md-6 col-md-offset-3">
            <div class="input-group input-group-sm">
                <input autofocus="enable" id="speedAlertValue" type="number" class="form-control"
                       placeholder="Speed alert value " value="{{ speed_value }}">
                {% csrf_token %}
                <span class="input-group-addon">km/h</span>
            </div>
        </div>
        <div class="col-md-12">
            <button type="button" class="btn btn-info pull-right btn-sm" onclick="setSpeedAlert()">Set speed alert</button>
            <button type="button" class="btn  btn-default pull-left btn-sm" onclick="$('#speedAlert').modal('hide')">Cancel</button>
        </div>
    </div>
</div>
</body>
</html>

realtime_visualization/map_service/templates/map_service/alerts/within.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <style>
        .fa-trash-o:hover {
            color: red;
        }
    </style>

    <script>
        $(".removeGeoFence").tooltip();

        $('.viewGeoFenceRow td:not(:last-child)').click(function () {
            viewFence(this.parentElement, 'WithIn');
        });

    </script>
</head>
<body>
<div class="modal-header"
     style="cursor: move;background: #f9f9f9;-webkit-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);-moz-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);">
    <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">
        <!-- TODO: Trigger bootstrap tooltip $('#aboutTileUrl').tooltip(); to enable tooltip -->
        Set <i>within</i> alerts
    </h4>
</div>
<div class="modal-body">
    <div class="row">
        <p class="text-info text-center">View current fences</p>

        <div class="">
            <table class="table table-hover">
                <thead>
                <tr>
                    <th>Fence Name</th>
                    <th>Query Name</th>
                    <th>Created On</th>
                    <th></th>
                </tr>
                </thead>
                <tbody>

                {% for geofence in geofences %}
                    <tr class="viewGeoFenceRow" style="cursor: pointer" data-areaName='{{ geofence.areaName }}'
                        data-queryName='{{ geofence.queryName}}' data-geoJson='{{ geofence.geoJson }}'>
                        <td>{{ geofence.areaName }}</td>
                        <td>{{ geofence.queryName}}</td>
                        <td>{{ geofence.createdTime }}</td>

                        <td onClick="removeGeoFence(this.parentElement,'WithIn')" class="removeGeoFence"
                            data-toggle="tooltip" title="Remove fence"><i class="fa fa-trash-o"></i></td>

                    </tr>

                {% empty %}
                    <div class="alert alert-danger" role="alert">
                        <strong>Oh snap!</strong> Can't find any geo-fence areas,please draw a new area or try again.
                    </div>
                {% endfor %}
                </tbody>
            </table>
        </div>
        <div style="margin-bottom: -15px" class="btn-group btn-group-justified">
            <div class="btn-group">
                <button style="background-color: #f4f4f4;" type="button" class="btn btn-default"
                        onclick="openTools('WithIn')">Draw area
                </button>
                {% csrf_token %}
            </div>
            <div class="btn-group">
                <button style="background-color: #f4f4f4;" type="button" class="btn  btn-default"
                        onclick="$('#editWithinGeoJSON').modal('toggle')">Enter area
                </button>
            </div>
            <!--<div class="btn-group">-->
            <!--<button style="background-color: #f4f4f4;" type="button" class="btn  btn-default" onclick="closeAll()">Cancel</button>-->
            <!--</div>-->
        </div>
    </div>
</div>
</body>
</html>

realtime_visualization/map_service/templates/map_service/xml/stationery_alert.html
<!DOCTYPE html>
<html>
<head lang="en">
    <meta charset="UTF-8">
    <title></title>
    <style>
        .fa-trash-o:hover{color:red;}
    </style>

    <script>
    $(".removeGeoFence").tooltip();

    $('.viewGeoFenceRow td:not(:last-child)').click(function () {
            viewFence(this.parentElement,'Stationery');
        });

    </script>
</head>
<body>
<div class="modal-header" style="cursor: move;background: #f9f9f9;-webkit-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);-moz-box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);box-shadow: inset 0px 0px 14px 1px rgba(0,0,0,0.2);">
    <button class="close" type="button" data-dismiss="modal" aria-hidden="true">&times;</button>
    <h4 class="modal-title">
        <!-- TODO: Trigger bootstrap tooltip $('#aboutTileUrl').tooltip(); to enable tooltip -->
        Set <i>Stationery</i> alerts
    </h4>
</div>
<div class="modal-body">
    <div class="row">
        <p class="text-info text-center">View current fences</p>
        <div class="">
        <table class="table table-hover">
              <thead>
                <tr >
                  <th>Stationery Name</th>
                  <th>Stationery Time</th>
                  <th>Query Name</th>
                  <th>Created On</th>
                  <th></th>
                </tr>
              </thead>
              <tbody>
                <%
                    var alerts = get('stationery');

                    if(alerts){

                        for each(var alert in alerts){
                            %>
                            <tr class="viewGeoFenceRow" style="cursor: pointer" data-stationeryTime='<%= alert.stationeryTime %>' data-areaName='<%= alert.areaName %>' data-queryName='<%= alert.queryName %>' data-geoJson='<%= alert.geoJson %>'>
                                <td><%= alert.areaName %></td>
                                 <td><%= alert.stationeryTime %></td>
                                <td><%= alert.queryName %></td>
                                <td><%= alert.createdTime %></td>
                                <td onClick="removeGeoFence(this.parentElement,'Stationery')" class="removeGeoFence" data-toggle="tooltip" title="Remove fence" ><i class="fa fa-trash-o"></i></td>
                            </tr>
                        <%
                         }
                    } else{
                        %>
                            <div class="alert alert-danger" role="alert">
                                  <strong>Oh snap!</strong> Can't find any geo-fence areas,please draw a new area or try again.
                            </div>
                        <%
                    }
                %>
            </tbody>
        </table>
        </div>
<div style="margin-bottom: -15px" class="btn-group btn-group-justified">
<div class="btn-group">
    <button style="background-color: #f4f4f4;" type="button" class="btn btn-default" onclick="openTools('Stationery')">Draw area</button>
</div>
<div class="btn-group">
    <button style="background-color: #f4f4f4;" type="button" class="btn  btn-default" onclick="$('#editWithinGeoJSON').modal('toggle')" >Enter area</button>
</div>
<!--<div class="btn-group">-->
<!--<button style="background-color: #f4f4f4;" type="button" class="btn  btn-default" onclick="closeAll()">Cancel</button>-->
<!--</div>-->
</div>
</div>
</div>
</body>
</html>

realtime_visualization/map_system/templates/map_system/content/nav_bar.html
<nav class="navbar navbar-inverse" role="navigation" style="width: 60%">
    <div class="navbar-header">
        <div class="navbar-icon-container">
            <a href="#left_side_pannel" data-uk-offcanvas class="navbar-icon pull-right visible-xs"
                    ><i class="fa fa-bars fa-lg" style="color: #FF9900"></i></a>
            <a href="#" class="navbar-icon pull-right visible-xs"
               onclick="$('.navbar-collapse').collapse('toggle');return false;"><i class="fa fa-search fa-lg"
                                                                                   style="color: #FF9900"></i></a>
        </div>
    </div>
    <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav">
            <li class="hidden-xs"><a href="#left_side_pannel" data-uk-offcanvas>
                <i class="fa fa-list" style="color: #FF9900"></i></a></li>
        <li>
            <button type="button" class="btn btn-success" onclick="show_density()">Show Density</button>
        </li>
        </ul>
        <ul class="nav navbar-nav navbar-right">

            <li class="dropdown">
                <ul class="dropdown-menu" role="menu">
                    <li>
                        <a href="#" data-toggle="collapse" data-target=".navbar-collapse.in"
                           onclick="$('#aboutModal').modal('show'); return false;">About</a>
                    </li>
                    <li><a href="#">Doc</a></li>
                    <li class="divider"></li>
                    <li><a href="controllers/logout.jag">Logout</a></li>
                </ul>
            </li>
        </ul>
    </div>
</nav>

realtime_visualization/map_system/templates/map_system/content/tools_panel.html
<div id="left_side_pannel" class="uk-offcanvas">
    <div class="uk-offcanvas-bar" style="box-shadow: 3px 14px 13px -2px #8b8b8b;background: #ffffff">
        <ul class="uk-nav uk-nav-offcanvas uk-nav-parent-icon" data-uk-nav>
            <li class="uk-parent" style="box-shadow: 0 2px 12px 1px #cccdbd;min-height: 50px;line-height: 25px;">
                <a href="#" style="min-height: 50px;">
                    <span style="color: #3dc4d5">X<sub style="font-size: medium;color:#ffaeea;"> Factors</sub></span>
                    System
                </a>
                <ul class="uk-nav-sub">
                    <li style="color: #969490">
                        X-Factor System allows users to see realtime human density.
                    </li>
                </ul>
            </li>
            <li class="uk-nav-header">Analysis</li>
            <li class="uk-parent">
                <a href="#"><i class="fa fa-pencil-square-o"></i> Time Series</a>
                <ul class="uk-nav-sub">
                    <!-- Set speed limit -->
                    <li>
                        <a style="margin-left: 20%;" data-toggle="modal" href="{% url 'services:get_speed' %}"
                           data-target="#commonModal"><i
                                class="fa fa-tachometer"></i> Seasonal</a>
                    </li>
                    <li><a style="margin-left: 20%;" data-toggle="modal"
                           href=""
                           data-target="#commonModal"><i class="fa fa-link"></i> Trend</a></li>
                    <li><a style="margin-left: 20%;" data-toggle="modal"
                           href="{% url 'services:get_stationery' %}" data-target="#commonModal">
                        <i class="fa fa-chain-broken"></i> Cyclic</a></li>
                </ul>
            </li>

            <!-- Historical data section -->
            <li class="uk-nav-header">Prediction</li>
            <li class="uk-parent">
                <a href="#"><i class="fa fa-history"></i> Trends</a>
                <ul class="uk-nav-sub">

                    <li><a style="margin-left: 20%;" data-toggle="modal"
                           href="{% url 'services:estimate_trend' %}"
                           data-target="#commonModal"><i class="fa fa-road"></i> Predicted Density</a></li>
                </ul>
            </li>
            <!-- Settings section -->
            <li class="uk-nav-header">Settings</li>

            <!-- Add new tile server url -->
            <li>
                <a data-toggle="modal" data-target="#addTileServer"><i class="fa fa-plus"></i> Add New Camera/Sensor</a>
            </li>
            <!-- Add new WMS server url -->
            <li>
                <a data-toggle="modal" data-target="#addWmsUrl"><i class="fa fa-globe"></i> Add WMS end point</a>
            </li>

            <!-- Place holders need to remove or replace-->
            <li class="uk-nav-header">
                System Administrtion
            </li>

            <li>
                <a onclick="setupWizard.show();return false;"><i style="color: #ff8905;" class="fa fa-cogs"></i>
                    Setup
                    Dashboard</a>
            </li>
        </ul>
    </div>
</div>